### ISSUE TITLE
docker module: incompatible with docker-py 1.2.x

### ISSUE THREAD

**Issue by hryamzik** [angstwad/docker.ubuntu#44]
See [here](https://github.com/ansible/ansible/issues/10879) and [here](https://github.com/ansible/ansible-modules-core/issues/1227) for more details. [Workaround](https://github.com/ansible/ansible/issues/10879#issuecomment-97738264) is installing an older version of docker-py:

```
  tasks:
    - name: Install docker-py
      pip: name=docker-py version=1.1.0
```

And it could be set with ```pip_version_docker_py```.

I'm not sure about a proper way to solve this. One of the solutions could be setting default ```pip_version_docker_py```  to 1.1.0 if ansible version is below some value.

**Comment by angstwad** [comment]
This was addressed in issue #40 and PR #41.  

Use a parameterized role, and set `pip_version_docker_py` to 1.1.  It was decided that since this is a transient issue in upstream packages that is due to be resolved, the default behavior should be to use the latest package, and the workaround to manually set a lower package version in the interim.
